# Generated by Django 4.2.8 on 2024-07-09 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nationalId', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLicenseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_motor_cycle', models.BooleanField(default=False)),
                ('is_motor_vehicle', models.BooleanField(default=False)),
                ('certificate_number', models.IntegerField()),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_type', models.CharField(choices=[('New', 'New Application'), ('Renewal', 'Renewal Application'), ('Reissue', 'Reissue Application')], max_length=20)),
                ('license_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Ready for Printing', 'Ready for Printing'), ('Renewal Pending', 'Renewal Pending'), ('Renewal Processing', 'Renewal Processing'), ('Renewed', 'Renewed'), ('Reissue Pending', 'Reissue Pending'), ('Reissue Processing', 'Reissue Processing'), ('Reissued', 'Reissued')], default='Pending', max_length=20)),
                ('previous_license_id', models.CharField(blank=True, max_length=255, null=True)),
                ('renewal_applied_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reissue_applied_at', models.DateTimeField(blank=True, null=True)),
                ('reissue_approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationalId.nationalid')),
            ],
        ),
    ]
