# Generated by Django 4.2.8 on 2024-07-10 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverslicenseapplication',
            name='id',
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='center_locations',
            field=models.CharField(default='Unknown location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='email',
            field=models.CharField(default='richiemugambi4@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='local_government_area',
            field=models.CharField(default='Some LGA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='phoneNumber',
            field=models.CharField(default='+254722314720', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='reissue_police_report',
            field=models.FileField(blank=True, null=True, upload_to='police_reports/'),
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='reissue_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='state',
            field=models.CharField(default='Some State', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverslicenseapplication',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
