# Generated by Django 4.2.8 on 2024-07-10 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
        ('application', '0002_remove_driverslicenseapplication_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverslicenseapplication',
            name='license_id',
        ),
        migrations.AddField(
            model_name='driverslicenseapplication',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='license.license'),
        ),
    ]
