# Generated by Django 4.2.8 on 2024-07-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_driverslicenseapplication_license_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslicenseapplication',
            old_name='user',
            new_name='nationalId',
        ),
    ]
