# Generated by Django 4.2.8 on 2024-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_alter_license_licenseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='licenseId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
